# 生产环境配置
spring:
  profiles:
    active: prod

# 生产环境的Spaces配置
digitalocean:
  spaces:
    access-key: ${DO_SPACES_ACCESS_KEY}
    secret-key: ${DO_SPACES_SECRET_KEY}
    region: ${DO_SPACES_REGION}
    bucket-name: ${DO_SPACES_BUCKET_NAME}

# 生产环境的日志级别
logging:
  level:
    org.example.spaces: INFO
    software.amazon.awssdk: WARN