# 开发环境配置
spring:
  profiles:
    active: dev

# 开发环境的Spaces配置
digitalocean:
  spaces:
    access-key: ${DO_SPACES_ACCESS_KEY}
    secret-key: ${DO_SPACES_SECRET_KEY}
    region: ${DO_SPACES_REGION}
    bucket-name: ${DO_SPACES_BUCKET_NAME}


# 开发环境日志检测
logging:
  level:
    org.example.spaces: DEBUG
    software.amazon.awssdk: DEBUG